# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 📓 Jon's Lab Notebook
email: jon.clucas@childmind.org
description: >- # this means to ignore newlines until "baseurl:"
  Day-to-day activities in the lab
baseurl: "/lab-notebook" # the subpath of your site, e.g. /blog
url: "https://shnizzedy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# google_analytics: 'UA-131540516-1' # Substitute this with your own GA key
twitter_username: Jon_Clucas
github_username:  shnizzedy
excerpt_separator: <!--more-->

timezone: America/New_York

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections_dir: _collections

collections:
  log:
    output: true
    permalink: /:collection/:year-:month-:day:output_ext
  projects:
    output: true
    permalink: /:collection/:title:output_ext
  specs:
    output: true
    permalink: /:collection/:title:output_ext
  
defaults:
  -
    scope:
      path: ""
      type: "log"
    values:
      category: "log"
      layout: "log"
  -
    scope:
      path: ""
      type: "projects"
    values:
      category: "project"
      layout: "post"
  -
    scope:
      path: ""
      type: "specs"
    values:
      category: "specification"  
      layout: "spec"

# Social media
twitter: Jon_Clucas
github: shnizzedy
linkedin: shnizzedy
facebook: shnizzedy
orcid: ""
zotero: ""
publons: ""
