# CPAC Data Configuration File
# Version 1.6.2
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- anat: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-1/anat/sub-0027224_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-1/func/sub-0027224_ses-1_task-rest_run-1_bold.nii.gz
    rest_run-2:
      scan: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-1/func/sub-0027224_ses-1_task-rest_run-2_bold.nii.gz
  site: site-1
  subject_id: '0027224'
  unique_id: '1'
- anat: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-2/anat/sub-0027224_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-2/func/sub-0027224_ses-2_task-rest_run-1_bold.nii.gz
    rest_run-2:
      scan: /Users/xinhui.li/data/IBA_TRT/sub-0027224/ses-2/func/sub-0027224_ses-2_task-rest_run-2_bold.nii.gz
  site: site-1
  subject_id: '0027224'
  unique_id: '2'
