# CPAC Data Configuration File
# Version 1.7.0
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- anat: 
    anat_run-1:
      scan: /media/ebs/data/IBATRT/IBA_TRT/0027234/session_1/anat_1/anat.nii.gz
    anat_run-2:
      scan: /media/ebs/data/IBATRT/IBA_TRT/0027234/session_1/anat_1/anat.nii.gz
  func:
    rest_run-1:
      scan: /media/ebs/data/IBATRT/IBA_TRT/0027234/session_1/rest_1/rest.nii.gz
    rest_run-2:
      scan: /media/ebs/data/IBATRT/IBA_TRT/0027234/session_1/rest_2/rest.nii.gz
  site: site-1
  subject_id: '0027234'
  unique_id: '1'
